spring.application.name=CRUD
#forma de criação do banco
spring.jpa.hibernate.ddl-auto=update

#URL de conexão com comando de criação se não existir
spring.datasource.url= jdbc:mysql://localhost:3306/crud?createDatabaseIfNotExist=true

#Usuario
spring.datasource.username=root
#senha
spring.datasource.password=admin